server:
  port: 9090

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: car-service
              uri: lb://CAR-SERVICE
              predicates:
                - Path=/carservice/**

  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: http://localhost:8080/realms/master/protocol/openid-connect/token
            user-name-attribute: preferred_username

        registration:
          admin-client:
            provider: keycloak
            client-id: admin_user
            client-secret: FSy9z7xahyY703bH2d4KFueRsg5at0GW
            authorization-grant-type: client_credentials
            client-authentication-method: client_secret_basic
            scope: admin

          user-client:
            provider: keycloak
            client-id: normal_user
            client-secret: uMukWHBq0nbxThipPlVXmiMU9tMCfAm0
            authorization-grant-type: client_credentials
            client-authentication-method: client_secret_basic
            scope: user

      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/master/protocol/openid-connect/certs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG